### ISSUE TITLE
latex error with spaces and single character argument after \frac in math mode

### ISSUE THREAD

**Issue by xanonid** [ftilmann/latexdiff#50]
Spaces seem to be not properly ignored in math mode.

While

```
\documentclass[]{article}
\begin{document}
$x=\frac {1+2} b $
\end{document}
```

and

```
\documentclass[]{article}
\begin{document}
$x=\frac 1 {def}$
\end{document}
```

are processed by latex properly, their `latexdiff` shows both wrong. This is probably connected to the
`ulem` package.

Wrapping the same term into an `equation` environment:

```
\documentclass[]{article}
\begin{document}
\begin{equation}
x=\frac {1+2} b
\end{equation}
```

and

```
\documentclass[]{article}
\begin{document}
\begin{equation}
x=\frac 1 {def}
\end{equation}
\end{document}
```

produces with `latexdiff`:

```
 ! Undefined control sequence.
l.28 \DIFaddend \MATHBLOCKequation
                                  {
? 

```

**Comment by ftilmann** [comment]
It's a documented limitation of latexdiff that command arguments should always be surrounded by curly braces and that there should be no space between a command and its arguments or between the arguments (with the option --allow-spaces the second requirement is relaxed). This is necessary because latexdiff would otherwise have to know how many arguments each command it encounters is expecting, quite an impossible task given the number of available packages. Having said this, \frac seems to lead to this type of problems somewhat frequently, so I will consider introducing a special preprocessing in that essentially will convert the frac expressions to a form that latexdiff can digest. I will leave this question open as a feature request but it might not happen very quickly.

**Comment by xanonid** [comment]
Thanks for your quick and clarifying answer and all your development efforts!

**Comment by ftilmann** [comment]
I think this should have been fixed with commit e9d2fbc

**Comment by julianuu** [comment]
I think it is not fixed, at least inside in an `equation` environment I still get errors for the cases mentioned by @xanonid. I would be happy to contribute those and other cases to the list in https://github.com/ftilmann/latexdiff/blob/master/latexdiff#L2569, would you want this @ftilmann?

**Comment by ftilmann** [comment]
Sure, complete MWE (old and new file) are useful/needed for debugging efforts. As this is supposed to work, this is theonly way to make progress.  Thanks

**Comment by ftilmann** [comment]
Was addressed by @julianuu 's pull request #246. Thank you
